---
# installation.yml

- name: installation - ensure nextcloud is unarchived in {{ nextcloud_web_root }}
  unarchive:
    src: '{{ nextcloud_repo_url  }}/nextcloud-{{ nextcloud_version }}.tar.bz2'
    remote_src: true
    dest: '/tmp'

- name: test if nextcloud was unarchived
  stat: path=/tmp/nextcloud
  register: nextcloud_stat

- name: Move nextcloud dir
  shell: "mv /tmp/nextcloud/* {{ nextcloud_web_root }}/"
  args: 
    creates="{{ nextcloud_web_root }}" 
  when: nextcloud_stat.stat.exists

# configure directories permissions
- include: 'permissions.yml'

- name: installation - ensure nextcloud installation is finished
  command: 'php {{ nextcloud_web_root }}/occ maintenance:install --database "mysql" --database-name "{{ nextcloud_mysql_db }}"  --database-user "{{ nextcloud_mysql_user }}" --database-pass "{{ nextcloud_mysql_pw }}" --admin-user "{{ nextcloud_admin_user }}" --admin-pass "{{ nextcloud_admin_pw }}" --data-dir "{{ nextcloud_data_root }}"'
  become: true
  become_user: nginx

- name: installation - ensure trusted domains are set
  command: 'php {{ nextcloud_web_root }}/occ config:system:set trusted_domains {{ item.0 }} --value "{{ item.1 }}"'
  become: true
  become_user: nginx
  with_indexed_items:
    - '{{ nextcloud_trusted_domains  }}'

- name: performance tuning - ensure the nextcloud cronjob exists and runs every 15 min
  cron:
    name: nextcloud
    minute: 15
    user: nginx
    job: 'php -f /var/www/nextcloud/cron.php'

# configure config.php system file
#- include: 'configuration.yml'