---
# task file for rbicker.nextcloud

- include: 'prerequisites.yml'

- name: ensure {{ nextcloud_web_root }} is present
  file:
    name: '{{ nextcloud_web_root }}'
    state: directory
  register: new_installation

- include: 'installation.yml'
  when: new_installation.changed

- name: check version string for upgrade
  shell: "{{ nextcloud_web_root }}/occ -V | grep -oE '[[:digit:]]+.[[:digit:]]+.[[:digit:]]+'"
  become: true
  become_user: nginx
  register: current_version
  when: not new_installation.changed
  changed_when: False

- name: fail the play when current version cannot be determined
  fail:
    msg: current nextcloud version cannot be determined
  when: not new_installation.changed and current_version.stdout == ''

- include: 'upgrade.yml'
  when: not new_installation.changed and current_version.stdout != nextcloud_version

- name: configure config.php system file
  include: 'configuration.yml'
  when: new_installation.changed or nextcloud_force_configuration
