---
# selinux.yml

- name: installation - ensure SELinux file context mapping definitions are correct
  sefcontext:
    target: '{{ item  }}'
    setype: httpd_sys_rw_content_t
  with_items:
    - '{{ nextcloud_data_root }}(/.*)?'
    - '{{ nextcloud_web_root }}/config(/.*)?'
    - '{{ nextcloud_web_root }}/apps(/.*)?'
    - '{{ nextcloud_web_root }}/.htaccess'
    - '{{ nextcloud_web_root }}/.user.ini'
  register:
    sefcontext

- name: installation - restorecon if SELinux file context was changed
  command: '{{ item  }}'
  when: sefcontext.changed
  with_items:
    - 'restorecon -Rv {{ nextcloud_data_root }}'
    - 'restorecon -Rv {{ nextcloud_web_root }}'

- name: installation - set SELinux boolean for redis
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
